name: Deploy on Sync or Push to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Setup SSH for Deployment
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          mkdir -p $HOME/.ssh/
          echo "$SSH_KEY" > $HOME/.ssh/staging.key
          chmod 600 $HOME/.ssh/staging.key
          cat >> $HOME/.ssh/config <<EOF
          Host staging
              HostName $SSH_HOST
              User $SSH_USER
              Port $SSH_PORT
              IdentityFile $HOME/.ssh/staging.key
              StrictHostKeyChecking no
          EOF

      - name: Deploy to Server
        env:
          DEPLOY_PATH: "~/labguy-server"  # Path on the server
        run: |
          ssh staging << 'EOF'
            cd $DEPLOY_PATH
            git pull origin main
            npm install
            npm run build
            pm2 restart www
          EOF
