name: Deploy to Server

on:
  workflow_run:
    workflows: ["Sync Fork"]
    types:
      - completed
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "22.5.1"

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          echo "Creating .ssh directory..."
          mkdir -p $HOME/.ssh/

          echo "Writing SSH key to staging.key..."
          echo "$SSH_KEY" > $HOME/.ssh/staging.key
          chmod 600 $HOME/.ssh/staging.key  # Set permissions for the private key

          echo "Creating SSH config file..."
          cat >> $HOME/.ssh/config <<EOF
          Host staging
              HostName $SSH_HOST
              User $SSH_USER
              Port $SSH_PORT
              IdentityFile $HOME/.ssh/staging.key
              StrictHostKeyChecking no
          EOF

      - name: Load environment variables
        run: |
          ssh staging "cat ~/labguy-server/.env" > .env
          set -a
          source .env
          set +a

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Check for new changes
        id: check_changes
        run: |
          # Check for new changes in the repository
          ssh staging << 'EOF'
            cd labguy-server
            git fetch origin main
            git diff --quiet origin/main
            if [ $? -eq 0 ]; then
              echo "No new changes. Skipping deployment."
              echo "{CHANGES}={value}" >> "$GITHUB_ENV"
            else
              echo "There are new changes. Proceeding with deployment."
              echo "{CHANGES}={value}" >> "$GITHUB_ENV"

            fi
          EOF

      - name: Deploy to Server
        if: ${{ env.CHANGES == 'true' }}
        run: |
          ssh staging << 'EOF'
            cd labguy-server
            git reset --hard
            git config pull.rebase true
            git pull origin main
            npm install
            npm run build
            pm2 restart www
          EOF
