- name: Fork Sync
  uses: tgymnich/fork-sync@v1.2.1
  with:
    # Owner of the forked repository
    owner: ${{ github.repository_owner }}
    
    # Token for the GitHub API
    github_token: ${{ secrets.GITHUB_TOKEN }}
    
    # Branch to track from the upstream repository
    head: main  # Change this if the upstream repo's branch is different
    
    # Branch to keep updated in your fork
    base: main  # Change this if your fork uses a different branch
    
    # Merge method to use (merge, squash, or rebase)
    merge_method: merge  # Optional, can be changed to "squash" or "rebase"
    
    # Title of the pull request created by the sync action
    pr_title: "Automatic Fork Sync"
    
    # Message in the pull request
    pr_message: "This PR merges changes from the upstream repository into this forked repository."
    
    # Ignore exceptions and continue if sync fails
    ignore_fail: true  # Optional; if set to true, the workflow won't fail on sync errors
