name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Triggered by manual button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.8
        with:
          base: main  
          head: main  
          
