name: Daily Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every day at midnight UTC
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/jakubkanna/labguy-server.git

      - name: Fetch and merge changes from upstream
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main || true  # Merge changes, ignore errors if up-to-date

      - name: Push changes to forked repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push origin main

      - name: Trigger Deployment Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const workflow_id = "deploy.yml";  // replace with exact name of deploy workflow file
            await github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref: "main"
            });
