name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Triggered by a manual button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.8
        with:
          # Set the owner to the current repository owner
          owner: ${{ github.repository_owner }}  # Automatically uses your fork's owner
          
          # Set the base branch to the branch in your fork to be updated
          base: main  # Replace with your fork's default branch if it's different (e.g., 'master')
          
          # Set the head branch to the branch in the upstream repository you want to sync from
          head: main  # Replace with the upstream's default branch if it's different (e.g., 'master')
          
          # Optionally, specify a merge method (merge, squash, rebase)
          merge_method: merge  # Default is 'merge'. You can change this to 'squash' or 'rebase'
          
          # Optional pull request title and message for better tracking
          pr_title: "Sync Fork with Upstream"
          pr_message: "This PR automatically syncs the fork with the upstream repository."
          
          # Ignore failures and continue with the sync even if there's an issue
          ignore_fail: true  # Set to true if you want the action to continue even on errors
